#!/bin/bash
# Usage is: "lisplog [slimeport] [data-db]"

git submodule init
git submodule update

ccl -R 200M \
    -e '(load "start.lisp")' \
    -e '(in-package :ll)' \
    -e "(start-swank $1)" \
    -e "(start $2)"
