#!/bin/bash
# Usage is: "lisplog [slimeport] [data-db]"

git submodule init
git submodule update

if [ "x$CCL" = 'x' ]; then
  CCL=ccl
fi
$CCL -R 200M \
    -e '(load "start.lisp")' \
    -e '(in-package :ll)' \
    -e "(start-swank $1)" \
    -e "(start $2)"
